# SPDX-License-Identifier: MIT
# Copyright (c) 2026 AgentOPsBase contributors
#
# Part of AgentOPsBase. You may use, modify, redistribute, and sell this work
# or derivatives (including commercially) without owing the copyright holders
# anything beyond what the MIT license requires. This file is licensed under
# the terms in the LICENSE file at the repository root. The software is
# provided "AS IS", without warranty; the copyright holders are not liable for
# this code or for what anyone does with it.
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ml_intermediate_api_app
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ml_intermediate_api?schema=public
      PORT: 3000
      AUTH_STATUS: off
      JWT_SECRET: dev_jwt_secret_change_me
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: ml_intermediate_api_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ml_intermediate_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
